import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pytest
import uuid
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db.base import Base
from app.models.available_model import AvailableModel
from app.models.enums import ModelProvider
from app.models.query_message import QueryMessage
from app.models.enums import MessageRole
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.dialects.postgresql import JSONB

# Import all other models so their schemas/tables are metadata-bound

DATABASE_URL = "sqlite:///:memory:"


@compiles(JSONB, "sqlite")
def compile_jsonb_sqlite(element, compiler, **kw):
    return "JSON"


@pytest.fixture(name="db")
def db_fixture():
    engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
    Base.metadata.create_all(bind=engine)
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=engine)


def test_create_available_model(db):
    # Test model creation
    model_id = uuid.uuid4()
    model = AvailableModel(
        id=model_id,
        display_name="Claude 4.5 Haiku",
        provider=ModelProvider.anthropic,
        model_string="claude-haiku-4-5-20251001",
        is_active=True,
    )
    db.add(model)
    db.commit()

    # Query model
    db_model = db.query(AvailableModel).filter(AvailableModel.id == model_id).first()
    assert db_model is not None
    assert db_model.display_name == "Claude 4.5 Haiku"
    assert db_model.provider == ModelProvider.anthropic
    assert db_model.model_string == "claude-haiku-4-5-20251001"
    assert db_model.is_active is True


def test_query_message_model_relationship(db):
    # Test message model relationship
    model = AvailableModel(
        id=uuid.uuid4(),
        display_name="Llama 3.3 70B",
        provider=ModelProvider.openrouter,
        model_string="meta-llama/llama-3.3-70b-instruct:free",
        is_active=True,
    )
    db.add(model)
    db.commit()

    session_id = uuid.uuid4()
    message = QueryMessage(
        id=uuid.uuid4(),
        session_id=session_id,
        role=MessageRole.assistant,
        content="Hello, I was generated by Llama 3.3!",
        model_id=model.id,
    )
    db.add(message)
    db.commit()

    # Fetch and check relations
    db_message = (
        db.query(QueryMessage).filter(QueryMessage.session_id == session_id).first()
    )
    assert db_message is not None
    assert db_message.model_id == model.id
    assert db_message.model is not None
    assert db_message.model.display_name == "Llama 3.3 70B"
    assert db_message.model.provider == ModelProvider.openrouter


def test_model_update_and_deactivate(db):
    # Test updating active status and metadata
    model_id = uuid.uuid4()
    model = AvailableModel(
        id=model_id,
        display_name="GPT OSS 120B",
        provider=ModelProvider.openrouter,
        model_string="openai/gpt-oss-120b:free",
        is_active=True,
    )
    db.add(model)
    db.commit()

    db_model = db.query(AvailableModel).filter(AvailableModel.id == model_id).first()
    assert db_model.is_active is True

    # Update active status
    db_model.is_active = False
    db_model.display_name = "GPT OSS 120B (Legacy)"
    db.commit()

    # Verify updates
    updated_model = (
        db.query(AvailableModel).filter(AvailableModel.id == model_id).first()
    )
    assert updated_model.is_active is False
    assert updated_model.display_name == "GPT OSS 120B (Legacy)"
