"""Add notifications table

Revision ID: 2619da2195eb
Revises: b102285a925d
Create Date: 2026-06-24 22:16:27.915173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2619da2195eb'
down_revision: Union[str, Sequence[str], None] = 'b102285a925d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('role_assigned', 'document_access_direct', 'document_access_inherited_hierarchy', 'document_access_inherited_department', 'department_added', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_document_id', sa.Uuid(), nullable=True),
    sa.Column('related_role_id', sa.Uuid(), nullable=True),
    sa.Column('related_department_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_tenant_id_name'), 'roles', type_='unique')
    op.create_unique_constraint('uq_tenant_role_dept', 'roles', ['tenant_id', 'name', 'parent_role_id', 'department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_role_dept', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_tenant_id_name'), 'roles', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_table('notifications')
    # ### end Alembic commands ###
