"""add_model_pricing_and_tenant_budget

Revision ID: 3cc0e8f53081
Revises: 7620b9baf174
Create Date: 2026-06-26 14:35:04.873829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc0e8f53081'
down_revision: Union[str, Sequence[str], None] = '7620b9baf174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('available_models', sa.Column('input_price_per_million', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('available_models', sa.Column('output_price_per_million', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('tenants', sa.Column('monthly_budget_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Update/Seed Claude models with their official rates
    op.execute(
        "UPDATE available_models SET input_price_per_million = 1.0000, output_price_per_million = 5.0000 WHERE model_string = 'claude-haiku-4-5-20251001'"
    )
    op.execute(
        "UPDATE available_models SET input_price_per_million = 3.0000, output_price_per_million = 15.0000 WHERE model_string = 'claude-sonnet-4-6'"
    )
    op.execute(
        "UPDATE available_models SET input_price_per_million = 5.0000, output_price_per_million = 25.0000 WHERE model_string = 'claude-opus-4-8'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'monthly_budget_limit')
    op.drop_column('available_models', 'output_price_per_million')
    op.drop_column('available_models', 'input_price_per_million')
    # ### end Alembic commands ###
