"""add google oauth fields to users

Revision ID: 6d165f45a301
Revises: b385dace7102
Create Date: 2026-06-12 14:10:49.725644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d165f45a301"
down_revision: Union[str, Sequence[str], None] = "b385dace7102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "has_password", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.create_unique_constraint(None, "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "has_password")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
