"""add_columns_to_database_access_policy

Revision ID: 79791adfa8cf
Revises: f706d99723eb
Create Date: 2026-07-08 22:37:18.908227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79791adfa8cf"
down_revision: Union[str, Sequence[str], None] = "f706d99723eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "database_access_policies", sa.Column("columns", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("database_access_policies", "columns")
    # ### end Alembic commands ###
