"""add_report_tables

Revision ID: 938cea4650b9
Revises: 11007cca0754
Create Date: 2026-07-14 14:21:04.648595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "938cea4650b9"
down_revision: Union[str, Sequence[str], None] = "11007cca0754"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="generating", nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('generating', 'complete', 'failed')", name="chk_report_status"
        ),
        sa.ForeignKeyConstraint(["generated_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["query_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reports_session", "generated_reports", ["session_id"], unique=False
    )
    op.create_index(
        "idx_reports_tenant", "generated_reports", ["tenant_id"], unique=False
    )
    op.create_table(
        "report_agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("step_name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed')", name="chk_run_status"
        ),
        sa.CheckConstraint(
            "step_name IN ('gather', 'cluster', 'synthesize', 'assemble', 'render', 'deliver')",
            name="chk_step_name",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"], ["generated_reports.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_report_runs_report", "report_agent_runs", ["report_id"], unique=False
    )
    op.alter_column(
        "query_messages",
        "resolved_model",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_messages",
        "resolved_model",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_index("idx_report_runs_report", table_name="report_agent_runs")
    op.drop_table("report_agent_runs")
    op.drop_index("idx_reports_tenant", table_name="generated_reports")
    op.drop_index("idx_reports_session", table_name="generated_reports")
    op.drop_table("generated_reports")
    # ### end Alembic commands ###
