"""add description column to documents

Revision ID: 989a9aa151dd
Revises: e8d06a25e67f
Create Date: 2026-06-19 16:40:07.205209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "989a9aa151dd"
down_revision: Union[str, Sequence[str], None] = "e8d06a25e67f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "description")
    # ### end Alembic commands ###
