"""add available models

Revision ID: b021e3a82fcf
Revises: 2619da2195eb
Create Date: 2026-06-25 14:19:09.018200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b021e3a82fcf"
down_revision: Union[str, Sequence[str], None] = "2619da2195eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "available_models",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("anthropic", "openrouter", name="modelprovider"),
            nullable=False,
        ),
        sa.Column("model_string", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.table_constraints "
            "WHERE constraint_name = 'notifications_related_evaluation_id_fkey' "
            "AND table_name = 'notifications'"
        )
    ).fetchone()
    if result:
        op.drop_constraint(
            "notifications_related_evaluation_id_fkey",
            "notifications",
            type_="foreignkey",
        )
    inspector = sa.inspect(conn)
    
    # Check notifications column before dropping
    columns = [col["name"] for col in inspector.get_columns("notifications")]
    if "related_evaluation_id" in columns:
        op.drop_column("notifications", "related_evaluation_id")

    # Check tables before dropping
    tables = inspector.get_table_names()
    if "evaluation_results" in tables:
        op.drop_table("evaluation_results")
    if "evaluation_runs" in tables:
        op.drop_table("evaluation_runs")
    if "query_logs" in tables:
        op.drop_table("query_logs")
    op.add_column("query_messages", sa.Column("model_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None,
        "query_messages",
        "available_models",
        ["model_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Seed default models
    available_models_table = sa.table(
        "available_models",
        sa.column("id", sa.Uuid()),
        sa.column("display_name", sa.String()),
        sa.column("provider", sa.Enum("anthropic", "openrouter", name="modelprovider")),
        sa.column("model_string", sa.String()),
        sa.column("is_active", sa.Boolean()),
    )

    import uuid

    op.bulk_insert(
        available_models_table,
        [
            {
                "id": uuid.uuid4(),
                "display_name": "Claude 4.5 Haiku",
                "provider": "anthropic",
                "model_string": "claude-haiku-4-5-20251001",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "Claude 4.6 Sonnet",
                "provider": "anthropic",
                "model_string": "claude-sonnet-4-6",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "Claude 4.8 Opus",
                "provider": "anthropic",
                "model_string": "claude-opus-4-8",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "Nemotron 3 Ultra 550B",
                "provider": "openrouter",
                "model_string": "nvidia/nemotron-3-ultra-550b-a55b:free",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "GPT OSS 120B",
                "provider": "openrouter",
                "model_string": "openai/gpt-oss-120b:free",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "Llama 3.3 70B",
                "provider": "openrouter",
                "model_string": "meta-llama/llama-3.3-70b-instruct:free",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "display_name": "Gemma 4 31B",
                "provider": "openrouter",
                "model_string": "google/gemma-4-31b-it:free",
                "is_active": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "query_messages", type_="foreignkey")
    op.drop_column("query_messages", "model_id")
    op.add_column(
        "notifications",
        sa.Column(
            "related_evaluation_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("notifications_related_evaluation_id_fkey"),
        "notifications",
        "evaluation_runs",
        ["related_evaluation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("evaluation_run_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("query_log_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "faithfulness_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "context_relevancy_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation_runs.id"],
            name=op.f("evaluation_results_evaluation_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_log_id"],
            ["query_logs.id"],
            name=op.f("evaluation_results_query_log_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("evaluation_results_pkey")),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "requested_by_user_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending", "running", "completed", "failed", name="evaluationstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("query_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "date_range_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "date_range_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_faithfulness",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_context_relevancy",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("evaluation_runs_requested_by_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("evaluation_runs_tenant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("evaluation_runs_pkey")),
    )
    op.create_table(
        "query_logs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "contexts",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("answer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("query_logs_tenant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("query_logs_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("query_logs_pkey")),
    )
    op.drop_table("available_models")
    # ### end Alembic commands ###
