"""add model_string to query_logs

Revision ID: b069380e0d10
Revises: ccd00ac05df2
Create Date: 2026-06-29 15:16:14.013435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b069380e0d10'
down_revision: Union[str, Sequence[str], None] = 'ccd00ac05df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('model_string', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'model_string')
    # ### end Alembic commands ###
