"""add_departments_and_relations

Revision ID: b102285a925d
Revises: c7a8b9d0e1f2
Create Date: 2026-06-23 16:31:56.806462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b102285a925d'
down_revision: Union[str, Sequence[str], None] = 'c7a8b9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_id_department_name')
    )
    op.add_column('document_access_policies', sa.Column('granted_via_department_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'document_access_policies', 'departments', ['granted_via_department_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'roles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'department_id')
    op.drop_constraint(None, 'document_access_policies', type_='foreignkey')
    op.drop_column('document_access_policies', 'granted_via_department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
