"""add collections table

Revision ID: c9e076881727
Revises: 938cea4650b9
Create Date: 2026-07-15 16:32:31.343450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9e076881727"
down_revision: Union[str, Sequence[str], None] = "938cea4650b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_collection_name_per_tenant"),
    )
    op.create_index(
        "idx_collections_tenant", "collections", ["tenant_id"], unique=False
    )
    op.add_column("documents", sa.Column("collection_id", sa.Uuid(), nullable=True))
    op.create_index(
        "idx_documents_collection", "documents", ["collection_id"], unique=False
    )
    op.create_foreign_key(
        "fk_documents_collection_id",
        "documents",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_documents_collection_id", "documents", type_="foreignkey")
    op.drop_index("idx_documents_collection", table_name="documents")
    op.drop_column("documents", "collection_id")
    op.drop_index("idx_collections_tenant", table_name="collections")
    op.drop_table("collections")
    # ### end Alembic commands ###
