"""make_citations_document_id_nullable_and_add_connection_id

Revision ID: cf1e01de4274
Revises: 812defcb65d0
Create Date: 2026-07-06 14:16:04.075116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf1e01de4274"
down_revision: Union[str, Sequence[str], None] = "812defcb65d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_citations", sa.Column("connection_id", sa.Uuid(), nullable=True)
    )
    op.alter_column(
        "query_citations", "document_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_foreign_key(
        None,
        "query_citations",
        "external_database_connections",
        ["connection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "query_citations", type_="foreignkey")
    op.alter_column(
        "query_citations", "document_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("query_citations", "connection_id")
    # ### end Alembic commands ###
