"""Add website to Tenant

Revision ID: e6eb9cfe9778
Revises: b5efd432b4c5
Create Date: 2026-06-12 17:46:26.951816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6eb9cfe9778'
down_revision: Union[str, Sequence[str], None] = 'b5efd432b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website')
    # ### end Alembic commands ###
