"""add file_size to documents

Revision ID: e8d06a25e67f
Revises: 4bd6768dcde2
Create Date: 2026-06-19 11:37:21.970515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8d06a25e67f"
down_revision: Union[str, Sequence[str], None] = "4bd6768dcde2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("file_size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_size")
    # ### end Alembic commands ###
